### ISSUE TITLE
CLI: Error when the specified directory does not exist.

### ISSUE THREAD

**Issue by taizan-hokuto** [taizan-hokuto/pytchat#11]
When the specified directory does not exist, the following error occurs.
```
Extracting...
 video_id: _video_id_
 channel:  channel_name
 title:    video_title
 output path: C:\temp\_video_id_.html
...Traceback (most recent call last):
  File "c:\projects\pytchat\.venv\Scripts\pytchat-script.py", line 11, in <module>
    load_entry_point('pytchat', 'console_scripts', 'pytchat')()
  File "c:\projects\pytchat\pytchat\cli\__init__.py", line 52, in main
    callback=_disp_progress
  File "c:\projects\pytchat\pytchat\tool\extract\extractor.py", line 92, in extract
    self.processor.finalize()
  File "c:\projects\pytchat\pytchat\processors\html_archiver.py", line 135, in finalize
    with open(self.save_path, mode='a', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:/temp/_video_id_.html'

```

**Comment by taizan-hokuto** [comment]
fixed ｖ0.1.3
