### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ruyihaoren** [taizan-hokuto/pytchat#14]
$ pytchat -v cdIu8tdMxRw
Traceback (most recent call last):
  File "/home/uk/.local/bin/pytchat", line 10, in <module>
    sys.exit(main())
  File "/home/uk/.local/lib/python3.8/site-packages/pytchat/cli/__init__.py", line 48, in main
    info = VideoInfo(video_id)
  File "/home/uk/.local/lib/python3.8/site-packages/pytchat/tool/videoinfo.py", line 84, in __init__
    self._parse(text)
  File "/home/uk/.local/lib/python3.8/site-packages/pytchat/tool/videoinfo.py", line 94, in _parse
    res = json.loads(result.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by rrzz** [comment]
Seeing this also, something must have changed on the YT side.

**Comment by EtianAM** [comment]
It only happens in CLI, with the common example it works.

**Comment by rrzz** [comment]
I believe the comments are no longer in the page returned and now delivered on execution of the js on the page which is not supported here

**Comment by EtianAM** [comment]
> I believe the comments are no longer in the page returned and now delivered on execution of the js on the page which is not supported here. I'd imagine all yt scrapers are broken right now.
> 
> Funny for me, I had a need for this two days ago and used it successfully, then tried yesterday and it no longer works because of this change on the YT side,

I don't know much about what you use it for, but for livestreams and through livechat() it still works. According to what I understand from the code, the function that fails is not the one in charge of reading the comments, but of getting other information, even so, that information "I think" is still available, I tried to fix it, but I'm not very good with regex.

This line:
```
pattern = re.compile(r"yt\.setConfig\({'PLAYER_CONFIG': ({.*})}\);")
```

Look for the content of a JS, it still exists (although I don't know if it contains the information it should), but it seems to have moved and the regex can't find it anymore

Some approaches I have achieved on regex (they do **NOT** work):
```
pattern = re.compile(r"yt\.setConfig\(\{'PLAYER_CONFIG': ({.*})\}\);")
pattern = re.compile(r"yt\.setConfig\({.*('PLAYER_CONFIG': {.*}).*}\);")
pattern = re.compile(r"yt\.setConfig\({.*'PLAYER_CONFIG': ({.*}).*}\);")
pattern = re.compile(r"yt\.setConfig\({(.*)'PLAYER_CONFIG': ({.*})(.*)}\);")
```

@taizan-hokuto Have you considered using bs4 (or something similar) instead of regex to search the script/information?
