### ISSUE TITLE
[not bug] Running ytchat in parallel with my code.

### ISSUE THREAD

**Issue by MarioMey** [taizan-hokuto/pytchat#28]
Sorry to post this here. I need to use ytchat with my python code that interacts with OBS. So, I need to run it in parallel. I use to use obs-websocket-py like this:

```
def source_set_video_file(source_input, video_file):
    ws.call(requests.SetSourceSettings(source_input, sourceSettings={'local_file': video_file})

threading.Thread(target=source_set_video_file, args=('archivo.mp4')).start()`)
```

I use threading because, every time I make a request to websocket, it takes a annoying time to go on with the rest of the code.

I tried to run ytchat with threadding... but I have this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/ssd-120gb/videoconfestejo/scripts/j_ytchat.py", line 61, in chat
    chat = pytchat.create(video_id=video_id)
  File "/media/ssd-120gb/videoconfestejo/scripts/pytchat/core/__init__.py", line 7, in create
    return PytchatCore(_vid, **kwargs)
  File "/media/ssd-120gb/videoconfestejo/scripts/pytchat/core/pytchat.py", line 84, in __init__
    signal.signal(signal.SIGINT, lambda a, b: self.terminate())
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

So, I tried LiveChatAsync. Asyncio is difficult to understand and more for me, that I'm not a programmer 🤷. The code in the wiki does work... but I don't know how to run in parallel so, I can run other python code. For example, while running pytchat, run:

```
while True:
    print('Foo!')
    time.sleep(1)
```

So, messages are printed and, every second, "Foo!" is also printed. Please... any help?

**Comment by taizan-hokuto** [comment]
Please try to use `interruptable=False` in constructor of pytchat object.

```diff
# "/media/ssd-120gb/videoconfestejo/scripts/j_ytchat.py", line 61
-    chat = pytchat.create(video_id=video_id)
+    chat = pytchat.create(video_id=video_id, interruptable=False)

**Comment by MarioMey** [comment]
Thanks, man! It worked.
