### ISSUE TITLE
有効なライブ配信でもLiveChatAsync()を呼んだあとすぐis_alive() == Falseになる

### ISSUE THREAD

**Issue by tomityu** [taizan-hokuto/pytchat#37]
いつも利用させてもらっています。

本日夕方頃から、LiveChatAsync()を呼んでもすぐにis_alive() == Falseとなり、
チャットの取得ができなくなっています。

```
async def monitor(self):
        livechat = LiveChatAsync(self.video_id, callback=self.fetchcallback)
        while livechat.is_alive():
            await asyncio.sleep(3)
        try:
            livechat.raise_for_status()
        except Exception as e:
            logger.error(e)
            logger.error(traceback.format_exc())
```

raise_for_status()の結果は以下です。
```
Traceback (most recent call last):
  File "/root/src/chat_monitor.py", line 30, in monitor
    livechat.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/pytchat/core_async/livechat.py", line 357, in raise_for_status
    raise self.exception
  File "/usr/local/lib/python3.9/site-packages/pytchat/core_async/livechat.py", line 348, in _task_finished
    self.listen_task.result()
  File "/usr/local/lib/python3.9/site-packages/pytchat/core_async/livechat.py", line 156, in _startlisten
    await self._listen(self.continuation)
  File "/usr/local/lib/python3.9/site-packages/pytchat/core_async/livechat.py", line 171, in _listen
    contents = await self._get_contents(continuation, client, headers)
  File "/usr/local/lib/python3.9/site-packages/pytchat/core_async/livechat.py", line 240, in _get_contents
    reload_continuation = self._parser.reload_continuation(
  File "/usr/local/lib/python3.9/site-packages/pytchat/parser/live.py", line 87, in reload_continuation
    self.raise_exception(exceptions.NoContents('Chat data stream is empty.'))
  File "/usr/local/lib/python3.9/site-packages/pytchat/parser/live.py", line 121, in raise_exception
    raise exception
pytchat.exceptions.NoContents: Chat data stream is empty.
```

YouTube側の仕様変更かなと思ってますが、どうでしょうか？

**Comment by taizan-hokuto** [comment]
ご報告ありがとうございます。v0.5.3で修正しました。
ターミナルで `pip install --upgrade pytchat` を実行してアップデートしてください。

Fixed at v0.5.3.

**Comment by tomityu** [comment]
ご対応ありがとうございます！
