### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorCertificateError

### ISSUE THREAD

**Issue by taizan-hokuto** [taizan-hokuto/pytchat#4]
# Summary

aiohttp.client_exceptions.ClientConnectorCertificateError occurs.

macOS Catalina v10.15.3

**Comment by taizan-hokuto** [comment]
```
Traceback (most recent call last):
  File "/Users/trtt/projects/pytchat/.venv/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 916, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/trtt/projects/pytchat/.venv/bin/pytchat", line 11, in <module>
    load_entry_point('pytchat', 'console_scripts', 'pytchat')()
  File "/Users/trtt/projects/pytchat/pytchat/cli/__init__.py", line 46, in main
    Extractor(video_id, 
  File "/Users/trtt/projects/pytchat/pytchat/tool/extract/extractor.py", line 82, in extract
    data = self._execute_extract_operations()
  File "/Users/trtt/projects/pytchat/pytchat/tool/extract/extractor.py", line 69, in _execute_extract_operations
    self._ready_blocks()
  File "/Users/trtt/projects/pytchat/pytchat/tool/extract/extractor.py", line 33, in _ready_blocks
    blocks = asyncdl.ready_blocks(
  File "/Users/trtt/projects/pytchat/pytchat/tool/extract/asyncdl.py", line 78, in ready_blocks
    blocks = loop.run_until_complete(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/trtt/projects/pytchat/pytchat/tool/extract/asyncdl.py", line 55, in _get_blocks
    return await asyncio.gather(*tasks)
  File "/Users/trtt/projects/pytchat/pytchat/tool/extract/asyncdl.py", line 60, in _create_block
    async with session.get(url, headers = headers) as resp:
  File "/Users/trtt/projects/pytchat/.venv/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/client.py", line 963, in __aenter__
    self._resp = await self._coro
  File "/Users/trtt/projects/pytchat/.venv/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/client.py", line 442, in _request
    conn = await self._connector.connect(
  File "/Users/trtt/projects/pytchat/.venv/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 507, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/trtt/projects/pytchat/.venv/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 838, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/Users/trtt/projects/pytchat/.venv/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 983, in _create_direct_connection
    raise last_exc
  File "/Users/trtt/projects/pytchat/.venv/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 960, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/trtt/projects/pytchat/.venv/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-macosx-10.9-x86_64.egg/aiohttp/connector.py", line 918, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.youtube.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
```

**Comment by taizan-hokuto** [comment]
Install certificates.command

![](https://raw.githubusercontent.com/taizan-hokuto/taizan-hokuto.github.io/master/statics/certif_mac.png)
